"""add device_index to settings

Revision ID: 0eaa9e275559
Revises: e8a8bc69371a
Create Date: 2026-06-29 10:28:44.526078

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '0eaa9e275559'
down_revision: str | Sequence[str] | None = 'e8a8bc69371a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('device_index', sa.Integer(), nullable=False, server_default='0')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('device_index')

    # ### end Alembic commands ###
