"""initial schema

Revision ID: 18755637d96f
Revises:
Create Date: 2026-06-29 01:23:31.483110

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "18755637d96f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sample",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("collected_at", sa.DateTime(), nullable=True),
        sa.Column("site", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("depth_cm", sa.Float(), nullable=True),
        sa.Column("container", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("preparation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sample", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sample_session_id"), ["session_id"], unique=False)

    op.create_table(
        "run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sample_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("objective", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("illumination", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("camera_settings", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["sample.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_sample_id"), ["sample_id"], unique=False)

    op.create_table(
        "recording",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fps", sa.Float(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recording", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recording_run_id"), ["run_id"], unique=True)

    op.create_table(
        "track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("first_frame_ts", sa.DateTime(), nullable=False),
        sa.Column("last_frame_ts", sa.DateTime(), nullable=False),
        sa.Column("start_video_ms", sa.Integer(), nullable=False),
        sa.Column("end_video_ms", sa.Integer(), nullable=False),
        sa.Column("n_frames", sa.Integer(), nullable=False),
        sa.Column("mask_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mean_area_px", sa.Float(), nullable=True),
        sa.Column("bbox_w_px", sa.Float(), nullable=True),
        sa.Column("bbox_h_px", sa.Float(), nullable=True),
        sa.Column("mean_speed_px_s", sa.Float(), nullable=True),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_track_flagged"), ["flagged"], unique=False)
        batch_op.create_index(batch_op.f("ix_track_label"), ["label"], unique=False)
        batch_op.create_index(batch_op.f("ix_track_run_id"), ["run_id"], unique=False)

    op.create_table(
        "frame",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sharpness", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("frame", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_frame_track_id"), ["track_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("frame", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_frame_track_id"))

    op.drop_table("frame")
    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_track_run_id"))
        batch_op.drop_index(batch_op.f("ix_track_label"))
        batch_op.drop_index(batch_op.f("ix_track_flagged"))

    op.drop_table("track")
    with op.batch_alter_table("recording", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recording_run_id"))

    op.drop_table("recording")
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_sample_id"))

    op.drop_table("run")
    with op.batch_alter_table("sample", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sample_session_id"))

    op.drop_table("sample")
    op.drop_table("session")
    # ### end Alembic commands ###
