"""add clip table

Revision ID: 7922d8417fc3
Revises: a2afa7f90d91
Create Date: 2026-06-29 09:54:24.133858

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '7922d8417fc3'
down_revision: str | Sequence[str] | None = 'a2afa7f90d91'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seconds_before', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clip_flagged'), ['flagged'], unique=False)
        batch_op.create_index(batch_op.f('ix_clip_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_clip_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clip_run_id'))
        batch_op.drop_index(batch_op.f('ix_clip_label'))
        batch_op.drop_index(batch_op.f('ix_clip_flagged'))

    op.drop_table('clip')
    # ### end Alembic commands ###
