"""add snapshot table

Revision ID: a2afa7f90d91
Revises: 18755637d96f
Create Date: 2026-06-29 02:36:57.582280

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'a2afa7f90d91'
down_revision: str | Sequence[str] | None = '18755637d96f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_flagged'), ['flagged'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshot_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshot_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_run_id'))
        batch_op.drop_index(batch_op.f('ix_snapshot_label'))
        batch_op.drop_index(batch_op.f('ix_snapshot_flagged'))

    op.drop_table('snapshot')
    # ### end Alembic commands ###
