"""add settings table

Revision ID: e8a8bc69371a
Revises: 7922d8417fc3
Create Date: 2026-06-29 10:14:14.765978

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'e8a8bc69371a'
down_revision: str | Sequence[str] | None = '7922d8417fc3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brightness', sa.Integer(), nullable=False),
    sa.Column('contrast', sa.Float(), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=False),
    sa.Column('wb_r', sa.Float(), nullable=False),
    sa.Column('wb_g', sa.Float(), nullable=False),
    sa.Column('wb_b', sa.Float(), nullable=False),
    sa.Column('invert', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
